version: '3'

tasks:
  build:
    cmds:
      - cmake -B build -GNinja
      - cmake --build build
    env:
      CXX: /usr/local/opt/llvm/bin/clang++
      CC: /usr/local/opt/llvm/bin/clang
      OpenBLAS_DIR: /usr/local/opt/openblas
    silent: true
  run:
    cmds:
      - ./build/physics_test
    silent: true
